.class public final Lo7/a$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lo7/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Lo7/a;I)[Ljava/lang/Object;
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lo7/a<",
            "TT;>;I)[TT;"
        }
    .end annotation

    new-instance p0, Li6/n;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Li6/n;-><init>(Ljava/lang/String;)V

    throw p0
.end method
